version: 2
jobs:
 build:
  docker:
    - image: debian:stretch
  steps:
    - checkout
    - run:
       name: Testing Again
       command: echo "testing Again"
 deploy:
   machine:
     enabled: true
   steps:
     - checkout
     - run:
        name: Check Docker Version
        #command: docker ps  
        command: heroku apps
     - run:
        name: Login to Heroku
        command: |
          #docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          docker login -u=$HEROKU_LOGIN -p=$HEROKU_API_KEY registry.heroku.com
          ls -la
          heroku container:push web --app heroku-docker-app-new
          heroku container:release web --app heroku-docker-app-new
workflows:
 version: 2
 build-deploy:
  jobs:
   - build
   - deploy:
      requires:
        - build
