version: 2
jobs:
 build:
  docker:
    - image: debian:stretch
  steps:
    - checkout
    - run:
       name: Testing Again
       command: echo "testing Again"
 deploy:
   machine:
     enabled: true
   steps:
     - checkout
     - run:
        name: Check Docker Version
        #command: docker ps  
        command: heroku apps
     - run: 
         name: Heroku CLI
         command: curl https://cli-assets.heroku.com/install.sh | sh
     - run:
        name: Login to Heroku
        command: |
          #docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          docker login -u=$HEROKU_LOGIN -p=$HEROKU_API_KEY registry.heroku.com
          ls -la
          docker build --rm=false -t registry.heroku.com/heroku-docker-app-new/web .
          docker images
          docker push registry.heroku.com/heroku-docker-app-new/web:latest
          heroku container:release web
workflows:
 version: 2
 build-deploy:
  jobs:
   - build
   - deploy:
      requires:
        - build
