version: 2
jobs:
 build:
  docker:
    - image: debian:stretch
  steps:
    - checkout
    - run:
       name: Testing Again
       command: echo "testing Again"
 deploy:
   machine:
     enabled: true
   steps:
     - checkout
     - run:
        name: Check Docker Version
        command: docker ps             
workflows:
 version: 2
 build-deploy:
  jobs:
   - build
   - deploy:
      requires:
        - build
