version: 2
jobs:
 build:
  docker:
    - image: debian:stretch
  steps:
    - checkout
    - run:
       name: Testing Again
       command: echo "testing Again"
 deploy:
   docker:
     - image: debain:stretch
   steps:
     - checkout
     - run:
         name: deploying to heroku 
         command: heroku apps
