version: 2
jobs:
 build:
   machine:
     enabled: true
   steps:
     - run: 
         name: Heroku CLI
         command: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku apps
          sudo apt-get update
   
